### ISSUE TITLE
Different color for 

### ISSUE THREAD

**Issue by ericbarefoot** [ericbarefoot/compact_proposal#30]
The color for `\cnote` and `\mnote` highlighting are the same, and with the new behavior that `\cnote` simply generates a bit of text if you provide an argument, it might be worthwhile seeing if a different color would help for either one.

**Comment by amoodie** [comment]
While you're at it, the current highlighter color is pretty awful in my opinion :grimacing:

**Comment by ericbarefoot** [comment]
which one? the yellow for pnote? or the grey for mnote?

**Comment by amoodie** [comment]
The `\pnote`. 
![notes](https://raw.githubusercontent.com/ericbarefoot/compact_proposal/master/notes_example.png)
