### ISSUE TITLE
keyword arguments to class?

### ISSUE THREAD

**Issue by amoodie** [ericbarefoot/compact_proposal#9]
is it possible to pass keyword arguments to the class? 

e.g., I want to use an endash (`--`) as the list marking (`\labelitemi`) instead of a star (`$\star$`). So I would use the `\documentclass` declaration as:
`\documentclass[....,labelitemi=--]{compact_proposal}`

If no keyword argument is supplied, then default to something (e.g., the star).

Maybe there is a package that supports parsing keyword arguments? Does `etoolbox`?

**Comment by amoodie** [comment]
This issue has been resolved with pull request #15 .

**Comment by ericbarefoot** [comment]
nvmd @amoodie did this
